### PR TITLE
Hi, I am Pritam. I want to upload my files to your repository. 

### PR DESCRIPTION
**Pull request by pritam-code-ai**
Hi, 
I want to upload my files and folders to your repository. As a mention, I have contacted you by call and messages. 
I have seperated my files and folders into seperate folders in your task folder. 
My seperate models are in- 

1.
tasks/computer-vision/image-generation. 

2.
tasks/natural-language-processing/sentiment-analysis. 

3. 
tasks/natural-language-processing/text-summarization. 

4. 
tasks/speech-synthesis-and-audio-analysis. 

I have done these code in ipynb jupyter notebook in python 3.6 and mlflow.

I used mlflow.tracking API in python to log parameters, metrics and files.

Please allow me to upload my files and folders. 

I am eagerly waiting for you to allow me to upload my files and folders to your repository. 

Hope to hear from you soon. 

Yours sincerely, 
Pritam

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@pritam-code-ai Imagine each AI task is standalone and does not require other tasks to function. In other words, you can run each machine learning model without involving any other machine learning model.

@lucky-singh Please comment on this pull request.

**Comment by lucky-singh** [comment]
Sure @slavakurilyak, let me give a try.

Hi @pritam-code-ai, great start and contribution. Here are my comments which I am providing by looking into NLP task and hope are applicable for CV  task as well.

- Could you please add information on README.md with beief about the task, and please mention that what kind of input we should provide and what output we could expect. This is my understanding but please update accordingly.
    - Input: Text sentence
    - Output: 
        - Category: Fact, Opinion
        - Sentiment: Positive, Neutral, Negative
- Our aspiration is to build an ai service and it would be fantastic if our task is reusable with others examples. Please add usage syntax examples for others to follow.
    - How to call the program? I am not sure if we call notebook, otherwise you can convert it to python file. 
    - Please drop statements which are not useful for model building, tracking or serving. Please refer [mlflow tutorial](https://mlflow.org/docs/latest/tutorial.html)
    - Please add details on how to pass sentence or file or both as a parameter?
    - Please add where outputs are stored and accessed?
- Please create conda.yaml and specify dependencies. please refer [mlflow examples](https://github.com/mlflow/mlflow/blob/master/examples/sklearn_elasticnet_diabetes/linux/conda.yaml) for details
- Please add [MLproject](https://github.com/mlflow/mlflow/blob/master/examples/sklearn_elasticnet_diabetes/linux/MLproject) file and define package dependency, input parameters and command to execute program.
- Please try to see, how this project can be served through model-uri, please see example on [mlflow](https://github.com/mlflow/mlflow#saving-and-serving-models) repository

- Could you please remove bulky files from repository and try to download from the source or generate as part of the workflow. Otherwise the repository will become huge in size and other contributors or users might lose interest at the first cloning attempt.

At last, I would like to mention again that it's a fantastic contribution and keep up the good work.

**Comment by pritam-code-ai** [comment]
Hi,
As @lucky-singh instructed me, I have done the changes and additionally, have added a new project as- tasks/speech-synthesis-and-audio-analysis. Please check these and allow me to upload the code on your repository.

I am eagerly waiting for your reply.

Hope to hear from you soon.

yours sincerely,
Pritam

**Comment by pritam-code-ai** [comment]
Hi Slava,
I have changed the code according lucky singh's instructions.
Please check my github code on pull request.

Yours sincerely,
Pritam

**Comment by pritam-code-ai** [comment]
Hi lucky singh,
I have changed the code according to your instructions.
Please check my github code on pull request.

Yours sincerely,
Pritam

**Comment by lucky-singh** [comment]
Hi Pritam,

Please allow me some time to get back to you.

I will review changes very soon.

Thanks,
Lucky

**Comment by lucky-singh** [comment]
New pull request has been created.

**Pull request closed without merging**
