### PR TITLE
Image Classification

### PR DESCRIPTION
**Pull request by 1subodh**
This is Image Classification based on scraped data.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@1subodh thanks for your first contribution! Please integrate [MLflow](https://github.com/mlflow/mlflow) into your pull request. At AI Platform, we use MLflow to manage machine learning models and log results.

**Comment by 1subodh** [comment]
@slavakurilyak I have added MLFLOW for logs and model.Please look into it.

**Comment by slavakurilyak** [comment]
@1subodh thanks very much! Please add `MLproject` file as well. Here's a simple [example](https://github.com/mlflow/mlflow/tree/master/examples/sklearn_elasticnet_wine) on how to accomplish this.

**Comment by 1subodh** [comment]
@slavakurilyak  added mlproject and conda.yaml files

**Comment by mlaradji** [comment]
Hi @slavakurilyak. I'm not sure what a good naming system would be for different tasks that tackle the same issue (e.g. image classification). A UUID is probably the best option for least conflict, but a proper name (such as StyleGAN) would be more descriptive. We might want to look into a database system.

**Comment by slavakurilyak** [comment]
@mlaradji we need to merge all image classification models into one. We need to make our AI Platform more flexible to allow for any dataset depending on user input. For inspiration, check out 
Uber's [Ludwig](https://github.com/uber/ludwig) project.

**Comment by slavakurilyak** [comment]
@1subodh Please revert your last commit and create a new pull request for your `few-shot learning` model. This will make it easier for other developers to review your work. Thanks in advance.

**Comment by slavakurilyak** [comment]
@1subodh Please revert your last commit and create a new pull request for your `language modeling` task. Separating your models into individual pull requests will make it easier for the Produvia team to provide you with feedback. Thanks again.

**Pull request closed without merging**
