### PR TITLE
Implement object detection task

### PR DESCRIPTION
**Pull request by lucky-singh**
Object detection service implementation as per my initial understanding.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@lucky-singh great work! 

Your next challenge is to abstract `inputs` and `outputs` into a YAML file. Check out Uber's [Ludwig](https://github.com/uber/ludwig) for inspiration on how to achieve modularity and extensibility using  data types and YAML files. Examples of Ludwig can be found [here](https://uber.github.io/ludwig/examples/).

**Comment by lucky-singh** [comment]
@slavakurilyak , I am looking into [MLflow- MLproject](https://github.com/mlflow/mlflow/blob/master/examples/pytorch/MLproject) and [ludwig - model_definition](https://uber.github.io/ludwig/examples/#simple-regression-fuel-efficiency-prediction) files and both seems to have similar information for inputs. However MLflow is disigned to work without registering inputs into MLproject and I couldn't find any example where outputs are specified.

Should I be focusing on writing a seperate yaml file and use it as inputs and outputs in mlflow run program? Or should I be focusing on parsing these files and create an artifact file with the desired details. I think second opton will keep MLflow project consistent and seperate YAML file will give ease of visibility. Please let me know your thoughs.

**Comment by slavakurilyak** [comment]
@lucky-singh Thanks for diving into MLflow and Ludwig!

Let's first consider why we are pursuing this project. The mission for our **AI Platform** is the AI-enabled automation of AI R&D tasks. The first step is to solve AI tasks, one at a time. 

One way to view AI tasks is from the perspective of:

1. inputs and 
2. goals.

Another way to view AI tasks is from perspective of:

1. input information, 
2. internal architecture, 
3. output modalities, and 
4. objective functions.

While there is not right or wrong way to achieve our mission, I think we can start with the easiest implementation. Since we are relying on MLflow as a code dependency, I think we can start by creating a YAML file for inputs in order to achieve consistency and modularity best practices.

**Comment by slavakurilyak** [comment]
@lucky-singh if you think the MLflow community can benefit from your ideas, feel free to share them to inspire others. Here are some of the ideas I previously shared: https://github.com/mlflow/mlflow/issues/created_by/slavakurilyak

**Comment by lucky-singh** [comment]
Sure, thank you for sharing.

**Pull request merged**
