### PR TITLE
Time Series Project

### PR DESCRIPTION
**Pull request by colleenfarrelly**
Hoping that this goes through and shows up this time. Thanks!

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@colleenfarrelly This is a good starting point. Please upload your scripts or notebooks for review.

**Comment by slavakurilyak** [comment]
@colleenfarrelly It looks like you are solving multiple tasks: time series analysis (part 1 of your code), time series forecasting (part 2 of your code), and "clustering" (task name is TBD).

**Comment by colleenfarrelly** [comment]
Hi Slava,


Yes, I tried to give a variety of time series tasks within a single dataset. This is typical of the data projects I've done in the past--multiple pieces to the project with the same data, particularly with time series. Thanks.


Sincerely,

Colleen Farrelly

________________________________

**Comment by colleenfarrelly** [comment]
Hi Slava,


I thought I had done this by posting? Is there a way to attach the data and script file directly using GitHub? It's a new tool for me--we usually used Jira/Confluence for version control. Thanks.


Sincerely,

Colleen Farrelly

________________________________

**Comment by slavakurilyak** [comment]
@colleenfarrelly Please push your latest changes to [your fork of ai-platform](https://github.com/colleenfarrelly/ai-platform)

**Comment by colleenfarrelly** [comment]
Hi Slava,


I'm not sure I understand. Do you mean adding the code and data files? Thanks.


Sincerely,

Colleen Farrelly

________________________________

**Comment by slavakurilyak** [comment]
@colleenfarrelly Yes

**Comment by colleenfarrelly** [comment]
Hi Slava,


I've added the documents. Please let me know if there is anything else you need at this point. Thank you.


Sincerely,

Colleen Farrelly

________________________________

**Comment by slavakurilyak** [comment]
@lucky-singh please create a new pull request for your [master](https://github.com/colleenfarrelly/ai-platform/tree/master) branch, which contains your latest commits. This pull request is for your [colleenfarrelly-patch-1](https://github.com/colleenfarrelly/ai-platform/tree/colleenfarrelly-patch-1) branch. Cheers!

**Comment by colleenfarrelly** [comment]
@slavakurilyak do you mean me or a lucky-singh person? I am Colleen.

**Comment by slavakurilyak** [comment]
@colleenfarrelly Yes, I was referring to you. I apologize for the confusion.

**Pull request closed without merging**
