### PR TITLE
Image Classification

### PR DESCRIPTION
**Pull request by ssravali**
This project is submission for the second round of the interview.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@ssravali Thanks for your contribution. Please add [MLflow](https://github.com/mlflow/mlflow) so other developers can improve upon your work.

**Comment by slavakurilyak** [comment]
@ssravali Thanks for your modification. Please add `MLproject` file to your directory. Here's an example of how to accomplish this:

https://www.mlflow.org/docs/latest/projects.html#mlproject-file

**Comment by slavakurilyak** [comment]
@ssravali Please convert your Jupyter notebook into Python scripts. This will allow you to add `MLproject` file. Here are three examples on how to accomplish this:

1. https://github.com/mlflow/mlflow/blob/master/examples/tensorflow/MLproject
2. https://github.com/mlflow/mlflow/blob/master/examples/multistep_workflow/MLproject
3. https://github.com/mlflow/mlflow/blob/master/examples/docker/MLproject

**Comment by ssravali** [comment]
@slavakurilyak I have changed the Jupyter notebook to a Python Script and i have added MLflow to it.

**Comment by slavakurilyak** [comment]
@ssravali Please update `README.md` file with code usage instructions and add `MLproject` file.

**Pull request closed without merging**
