### PR TITLE
Some changes for Windows support

### PR DESCRIPTION
**Pull request by brianleahy**
These proposed changes to time-series-forecasting:
1. Fix a filename convention that's incompatible with Windows.
2. Remove Conda package requirements that don't appear to actually be required.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@brianleahy Please upload your `time series classification` model as a separate pull request. This will make it easier to evaluate your pull request.

**Comment by brianleahy** [comment]
@slavakurilyak  As far as I can tell, my pull request #125 is just my time series classification.  It should cover just 4 commits: the initial upload, then three more commits correcting the ReadMe file once I could see it rendered on GitHub.
If you're seeing these Windows compatibility commits in there as well, please let me know and I'll have to re-clone and do the TSC piece right with a branch from the start.

**Comment by slavakurilyak** [comment]
@brianleahy Your pull request changes two folders `time-series-forecasting` and `time-series-classification`. Please revert your latest commit (https://github.com/produvia/ai-platform/pull/104/commits/c4a8f3323021147f30d804dd77c686cb306d9a80) and create a new pull request for your TSC work.

**Comment by brianleahy** [comment]
Ah, I see it now.  I accidentally got that commit into both branches when I was separating my two pieces of work.  Thanks for pointing this out.
Do you still need a new pull request?  Alternatively I can create and cherry-pick a branch that has just the Windows commits without the TSC commit-then-revert if that would be better.

**Comment by slavakurilyak** [comment]
@brianleahy Thanks for making this change. Feel free to create a new pull request for your TSC model

**Comment by brianleahy** [comment]
@slavakurilyak Ooh, I hope I'm not being blind again.  I've looked over pull request #125  carefully just now, and as far as I can tell it's just the TSC work that I did.  It looks to me like I kept that branch clean.  If you're seeing something I'm missing, could you comment over on #125  for me?  Thanks much!

**Pull request closed without merging**
