### PR TITLE
Time Series Prediction

### PR DESCRIPTION
**Pull request by varshabudihal**
ipynb of the RNN model to predict the Apple stock pricing

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@varshabudihal Thanks for your first contribution. Please add [MLflow](https://github.com/mlflow/mlflow) into your codebase

**Comment by slavakurilyak** [comment]
@varshabudihal Please add `MLproject` to your folder. See [MLflow examples](https://github.com/mlflow/mlflow/tree/master/examples/) on how to accomplish this.

**Comment by slavakurilyak** [comment]
@varshabudihal Thanks for making these modifications.

**Comment by Akeemedes** [comment]
Hello @varshabudihal, thanks for the input. Could you provide details on how to use this in your readme.md file?

**Comment by slavakurilyak** [comment]
@mlaradji please review this contribution

**Pull request closed without merging**
