### PR TITLE
Traffic-Sign Image Generation based on GAN

### PR DESCRIPTION
**Pull request by ra9hur**
Here is Traffic-Sign Image Generation as a new task for Computer Vision. 
Looking forward to your response.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@ra9hur This is a great starting point! Please complete the following revisions to make the pull request smaller in foot-print:

1. Remove 84+ training images under: tasks/computer-vision/image-generation/images/train/
2. Remove `mlruns` folder which has 372+ files: tasks/computer-vision/image-generation/mlruns/

**Comment by ra9hur** [comment]
As suggested, have removed mlruns folder and also files in the train folder.
Please review and let me know, if it looks OK now.

**Review by mlaradji — CHANGES_REQUESTED** [review]
Hi @ra9hur. Thank you for your pull request! 

I am running your model in a Google Colab [notebook](https://colab.research.google.com/drive/1U7fCr6L4l2a8JPGCL9ZYBfEXr9jGApv_). Feel free to add comments to it and/or copy it.

I am having trouble running your model on my setup, and I have identified some potential issues (the full error logs are below):
1. Running `mlflow run .` causes an error. I think it is probably because the `conda.yaml` file contains `\t` (tab) characters:
```
     File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 310, in fetch_more_tokens
        % utf8(ch), self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: while scanning for the next token
    found character '\t' that cannot start any token
      in "<unicode string>", line 3, column 3:
          	- defaults
          ^ (line: 3)
```
This should be fixable by changing the tabs to spaces. It's weird that the yaml parser doesn't know how to handle tab characters.

2. I ran `mlflow run . --no-conda`, which executes without error. However, it seems that only the second command in the MLproject is evaluated:
```
entry_points:
  main:
    command: "python Traffic_Signs_GAN_train.py"
    command: "python Traffic_Signs_GAN_evaluate.py"
```
I believe that MLproject should have only one 'command' definition per entry point, as otherwise only the last definition is used.

3. Running `python Traffic_Signs_GAN_train.py` causes a `FileNotFoundError` exception to be raised:
```
Traceback (most recent call last):
  File "Traffic_Signs_GAN_train.py", line 359, in <module>
    dataset = load_preprocess_real_data(base_dir, class_val)
  File "Traffic_Signs_GAN_train.py", line 151, in load_preprocess_real_data
    with open(training_file, mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './traffic-signs-data/train.p'
```

### Error Logs
#### `mlflow run .`
```
/usr/local/lib/python3.6/dist-packages/pygments/util.py:27: DeprecationWarning: Flags not at the start of the expression '<(.+?)(\\s.*?)?>.*?</' (truncated)
  tag_re = re.compile(r'<(.+?)(\s.*?)?>.*?</.+?>(?uism)')
/usr/local/lib/python3.6/dist-packages/IPython/utils/module_paths.py:29: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2019/10/11 14:27:04 INFO mlflow.projects: === Creating conda environment mlflow-82d5017f98f25d2ccb50aa72779927aca50f305a ===

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/root/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/root/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 77, in execute
        directory=os.getcwd())
      File "/root/miniconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/root/miniconda3/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/root/miniconda3/lib/python3.7/site-packages/conda_env/env.py", line 144, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/root/miniconda3/lib/python3.7/site-packages/conda_env/env.py", line 129, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/root/miniconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 640, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 194, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 106, in compose_node
        if self.parser.check_event(AliasEvent):
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 144, in check_event
        self.current_event = self.state()
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 577, in parse_block_mapping_value
        if self.scanner.check_token(ValueToken):
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 160, in check_token
        self.fetch_more_tokens()
      File "/root/miniconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 310, in fetch_more_tokens
        % utf8(ch), self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: while scanning for the next token
    found character '\t' that cannot start any token
      in "<unicode string>", line 3, column 3:
          	- defaults
          ^ (line: 3)

`$ /root/miniconda3/bin/conda-env create -n mlflow-82d5017f98f25d2ccb50aa72779927aca50f305a --file /content/aip-ra9hur/tasks/computer-vision/image-generation/conda.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/root/miniconda3
          LD_LIBRARY_PATH=/usr/lib64-nvidia
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/b
                          in:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-
                          sdk/bin:/opt/bin:/root/miniconda3/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : /root/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.14.137+ ubuntu/18.04.3 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Traceback (most recent call last):
  File "/usr/local/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/cli.py", line 137, in run
    run_id=run_id
  File "/usr/local/lib/python3.6/dist-packages/mlflow/projects/__init__.py", line 285, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/projects/__init__.py", line 164, in _run
    conda_env_name = _get_or_create_conda_env(project.conda_env_path)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/projects/__init__.py", line 518, in _get_or_create_conda_env
    conda_env_path], stream_output=True)
  File "/usr/local/lib/python3.6/dist-packages/mlflow/utils/process.py", line 38, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1
```
#### `mlflow run . --no-conda`
```
/usr/local/lib/python3.6/dist-packages/pygments/util.py:27: DeprecationWarning: Flags not at the start of the expression '<(.+?)(\\s.*?)?>.*?</' (truncated)
  tag_re = re.compile(r'<(.+?)(\s.*?)?>.*?</.+?>(?uism)')
/usr/local/lib/python3.6/dist-packages/IPython/utils/module_paths.py:29: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2019/10/11 14:42:03 INFO mlflow.projects: === Created directory /tmp/tmp5ln9vo7a for downloading remote URIs passed to arguments of type 'path' ===
2019/10/11 14:42:03 INFO mlflow.projects: === Running command 'python Traffic_Signs_GAN_evaluate.py' in run with ID 'c318138979a84d6784cb1e3d7685fbc0' === 
Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:190: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:197: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:203: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-10-11 14:42:06.335391: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-10-11 14:42:06.335665: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7889100 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-11 14:42:06.335723: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-10-11 14:42:06.337657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-10-11 14:42:06.415588: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-11 14:42:06.416515: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x78899c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2019-10-11 14:42:06.416558: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2019-10-11 14:42:06.416771: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-11 14:42:06.417454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
2019-10-11 14:42:06.417845: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-11 14:42:06.419386: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-11 14:42:06.420604: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-10-11 14:42:06.420961: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-10-11 14:42:06.422579: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-10-11 14:42:06.423806: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-10-11 14:42:06.427720: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-10-11 14:42:06.427822: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-11 14:42:06.428513: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-11 14:42:06.429195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-10-11 14:42:06.429254: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-10-11 14:42:06.430602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-10-11 14:42:06.430635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-10-11 14:42:06.430647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-10-11 14:42:06.430786: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-11 14:42:06.431486: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-11 14:42:06.432172: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-10-11 14:42:06.432232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10805 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:207: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:216: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:223: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

2019-10-11 14:42:07.294322: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-10-11 14:42:07.444833: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
<Figure size 1000x4000 with 20 Axes>
2019/10/11 14:42:12 INFO mlflow.projects: === Run (ID 'c318138979a84d6784cb1e3d7685fbc0') succeeded ===
```

#### `python Traffic_Signs_GAN_train.py`
```
Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

Generator Model Summary
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 65536)             6619136   
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 65536)             0         
_________________________________________________________________
reshape_1 (Reshape)          (None, 16, 16, 256)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 16, 16, 256)       1638656   
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 16, 16, 256)       0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 32, 32, 128)       524416    
_________________________________________________________________
leaky_re_lu_3 (LeakyReLU)    (None, 32, 32, 128)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 128)       409728    
_________________________________________________________________
leaky_re_lu_4 (LeakyReLU)    (None, 32, 32, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 32, 128)       409728    
_________________________________________________________________
leaky_re_lu_5 (LeakyReLU)    (None, 32, 32, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 32, 32, 3)         18819     
=================================================================
Total params: 9,620,483
Trainable params: 9,620,483
Non-trainable params: 0
_________________________________________________________________
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 65536)             6619136   
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 65536)             0         
_________________________________________________________________
reshape_1 (Reshape)          (None, 16, 16, 256)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 16, 16, 256)       1638656   
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 16, 16, 256)       0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 32, 32, 128)       524416    
_________________________________________________________________
leaky_re_lu_3 (LeakyReLU)    (None, 32, 32, 128)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 128)       409728    
_________________________________________________________________
leaky_re_lu_4 (LeakyReLU)    (None, 32, 32, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 32, 128)       409728    
_________________________________________________________________
leaky_re_lu_5 (LeakyReLU)    (None, 32, 32, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 32, 32, 3)         18819     
=================================================================
Total params: 9,620,483
Trainable params: 9,620,483
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Discriminator Model Summary
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 32, 32, 3)         0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 30, 30, 64)        1792      
_________________________________________________________________
leaky_re_lu_6 (LeakyReLU)    (None, 30, 30, 64)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 14, 14, 128)       73856     
_________________________________________________________________
leaky_re_lu_7 (LeakyReLU)    (None, 14, 14, 128)       0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 6, 6, 128)         147584    
_________________________________________________________________
leaky_re_lu_8 (LeakyReLU)    (None, 6, 6, 128)         0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 2, 2, 256)         295168    
_________________________________________________________________
leaky_re_lu_9 (LeakyReLU)    (None, 2, 2, 256)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1024)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025      
=================================================================
Total params: 519,425
Trainable params: 519,425
Non-trainable params: 0
_________________________________________________________________
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 32, 32, 3)         0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 30, 30, 64)        1792      
_________________________________________________________________
leaky_re_lu_6 (LeakyReLU)    (None, 30, 30, 64)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 14, 14, 128)       73856     
_________________________________________________________________
leaky_re_lu_7 (LeakyReLU)    (None, 14, 14, 128)       0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 6, 6, 128)         147584    
_________________________________________________________________
leaky_re_lu_8 (LeakyReLU)    (None, 6, 6, 128)         0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 2, 2, 256)         295168    
_________________________________________________________________
leaky_re_lu_9 (LeakyReLU)    (None, 2, 2, 256)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1024)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025      
=================================================================
Total params: 519,425
Trainable params: 519,425
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3657: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Adversarial Network Model Summary
Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         (None, 100)               0         
_________________________________________________________________
model_1 (Model)              (None, 32, 32, 3)         9620483   
_________________________________________________________________
model_2 (Model)              (None, 1)                 519425    
=================================================================
Total params: 10,139,908
Trainable params: 9,620,483
Non-trainable params: 519,425
_________________________________________________________________
Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         (None, 100)               0         
_________________________________________________________________
model_1 (Model)              (None, 32, 32, 3)         9620483   
_________________________________________________________________
model_2 (Model)              (None, 1)                 519425    
=================================================================
Total params: 10,139,908
Trainable params: 9,620,483
Non-trainable params: 519,425
_________________________________________________________________
Traceback (most recent call last):
  File "Traffic_Signs_GAN_train.py", line 359, in <module>
    dataset = load_preprocess_real_data(base_dir, class_val)
  File "Traffic_Signs_GAN_train.py", line 151, in load_preprocess_real_data
    with open(training_file, mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './traffic-signs-data/train.p'
```

**Comment by ra9hur** [comment]
Hi @mlaradji, Thanks for the detail review comments. Have made a few changes and now, all those that you mentioned seems to be fixed. Here are the changes:

Change
• conda.yaml
∘ Tabs removed
∘ Changes to install versions

• MLproject
∘ Fixed "mlflow run ." issue
∘ Works with parameters

• train.p & test.p
∘ Links to download data files have been provided in Readme and hence was not included in the earlier submission.
∘ Since these files are big, not able to upload them to github
∘ I have a copy on Google Drive. Sharing the link to download if that helps.
∘ https://drive.google.com/open?id=1zhbTU3_mq9JYrAT2MMmVdnpAVJCDTkXi

• Traffic_Signs_GAN_train.py
∘ Commented out mlflow.keras.autolog() since this line was raising error
∘ Works with command-line parameters
∘ Restoring weights from "goodrun" folder

• Traffic_Signs_GAN_evaluate.py
∘ Commented out mlflow.keras.autolog()
∘ Works with command-line parameters
∘ Restoring weights from "goodrun" folder

• "goodrun" folder included to avoid overwriting weights

• README updated for usage instructions since scripts now work with command-line parameters

Please review and let me know for any further changes.

**Comment by ra9hur** [comment]
Hi @mlaradji, 

Regarding the below issue -
3. Running python Traffic_Signs_GAN_train.py causes a FileNotFoundError exception to be raised:

To fix this, made changes to the code so that even while executing the python script, it downloads the dataset. So, user NEED NOT refer README link, download manually.

Please check and let me know, if you still face any problems.

**Comment by ra9hur** [comment]
Hi @mlaradji / @slavakurilyak,

Hope you got a chance to review my prior submission. Awaiting your feedback, please let me know for any further changes required.

**Pull request closed without merging**
