### PR TITLE
Time Series Forecasting

### PR DESCRIPTION
**Pull request by HarshiniDevathi2**
Predicting the number of residents in Australia and the sales based on time series data available in R

### CODE REVIEW

**Comment by HarshiniDevathi2** [comment]
@slavakurilyak i have uploaded the files to tasks/time-series/time-series-forecasting. Also, I have added the README file.

**Comment by HarshiniDevathi2** [comment]
@slavakurilyak I have added MLproject as per the example.

**Comment by slavakurilyak** [comment]
@HarshiniDevathi2 Thanks! Please add code usage and dataset instructions to your `README.txt`

**Comment by slavakurilyak** [comment]
See #127

**Pull request closed without merging**
