### PR TITLE
Image Classification

### PR DESCRIPTION
**Pull request by MohamedAliHabib**
The files contain:

1. The code in IPython notebooks.
2. the data in the folder named 'augmented data'.
3. The mlflow runs file in the folder named 'mlruns'.
4. The 'logs' file that contains logs you can visualize in tensorboard.
5. The 'models' file which contains the files of the models that have been trained, so that you can load them and use them.
6. A descriptive README file.
7. Some visualizations as image files.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@MohamedAliHabib Thanks for opening this pull request. To clarify, are you performing brain tumor segmentation or image classification? Also, you uploaded 2,000+ `augmented data` images with your pull request. To reduce the size of your contribution, please delete the `augmented data` folder and include dataset download instructions and code usage instructions to your `README.md` file.

**Comment by MohamedAliHabib** [comment]
I'm performing image classification. Okay, will do.

**Comment by slavakurilyak** [comment]
@MohamedAliHabib Great thanks! Please add `mlruns/` to your `.gitignore` file. ([Source](https://github.com/mlflow/mlflow/blob/master/.gitignore))

**Comment by MohamedAliHabib** [comment]
@slavakurilyak `mlruns/` is already included in `.gitignore ` [here](https://github.com/MohamedAliHabib/ai-platform/blob/master/.gitignore)

**Comment by MohamedAliHabib** [comment]
@slavakurilyak  I can delete `mlruns/` folder, if you want.

**Comment by slavakurilyak** [comment]
@MohamedAliHabib yes, please do.

**Comment by MohamedAliHabib** [comment]
@slavakurilyak  Sure, will do. I uploaded it because I wanted to make easier to view, without having to run the code.

**Comment by slavakurilyak** [comment]
@MohamedAliHabib Please add `MLproject` file to your pull request

**Comment by slavakurilyak** [comment]
@MohamedAliHabib Please add `conda.yaml` referenced in your `MLproject`. Here is a `requirements.txt` file to help you get started with dependencies:

```
mlflow==1.0.0
numpy==1.16.4
Keras==2.2.4
matplotlib==3.1.1
tensorflow==1.13.1
opencv_python==4.1.1.26
imutils==0.5.3
scikit_learn==0.21.3
```

**Comment by MohamedAliHabib** [comment]
I've added `MLproject` to the pull request. Please note that I've added also 3 additional files.
`Data Augmentation.py` and `Brain Tumor Detection.py` python files, since I've used jupyter notebook. And, a `bash file` to execute these files using the command in the `MLproject` file.

**Comment by MohamedAliHabib** [comment]
Thanks @slavakurilyak  for follow-up. I hope I didn't forget any file. If you wanted me to add another file, please ask and I'll be happy to do so.

**Comment by slavakurilyak** [comment]
@MohamedAliHabib Please remove bash file and update your `MLproject` file to: 
```
command: "python 'Data Augmentation'.py; python 'Brain Tumor Detection.py';"
```
or similar...

Also, when running your task, I receive the following error:
```
Traceback (most recent call last):
  File "Data Augmentation.py", line 26, in <module>
    get_ipython().run_line_magic('matplotlib', 'inline')
NameError: name 'get_ipython' is not defined
```

**Comment by slavakurilyak** [comment]
@MohamedAliHabib I ran your updated code and received the following error:

```
Traceback (most recent call last):
  File "Data Augmentation.py", line 92, in <module>
    augment_data(file_dir=yes_path, n_generated_samples=6, save_to_dir=augmented_data_path+'yes')
NameError: name 'yes_path' is not defined
Traceback (most recent call last):
  File "Brain Tumor Detection.py", line 109, in <module>
    ex_new_img = crop_brain_contour(ex_img, True)
  File "Brain Tumor Detection.py", line 53, in crop_brain_contour
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.1) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Pull request closed without merging**
