### PR TITLE
Integrate: Speech Synthesis and Audio Analysis

### PR DESCRIPTION
**Pull request by mlaradji**
This pull request is based on #28. It adds a new speech synthesis and audio analysis task in `tasks/speech/speech-synthesis`.

### CODE REVIEW

**Comment by mlaradji** [comment]
This pull request is ready to be accepted. Thank you for the pull request @pritam-code-ai!

@pritam-code-ai, it slipped my mind that because I copied the directory myself, you are not listed as a contributor on this pull request. If you are not concerned about this, let me know and I can just merge this pull request.

Otherwise, we can fix this. Please do one of the following on your local repo:
#### Option 1: Keep your current repository
```
# Add the produvia remote and fetch its branches.
git remote add produvia https://github.com/produvia/ai-platform.git
git fetch produvia
# Create a branch off produvia/master branch and push that to your repo.
git checkout -b produvia --track produvia/master
git pull
git checkout -b new-master
git remote add pritam-code-ai https://github.com/pritam-code-ai/ai-platform.git
git push pritam-code-ai
## Copy your work directory to `tasks/speech/speech-synthesis`
# ...
# After copy, commit and push changes.
git add .
git commit -m "[COMMIT MESSAGE]" # insert COMMIT MESSAGE
git push
```

#### Option 2: Delete current repository
This is probably the easier option. Steps:
1. Clone the https://github.com/pritam-code-ai/ai-platform in your computer to keep a local copy of the data. 
2. On GitHub, delete the https://github.com/pritam-code-ai/ai-platform repository.
3. On GitHub, fork the https://github.com/produvia/ai-platform repository. You should now have a new repository at https://github.com/pritam-code-ai/ai-platform that is up-to-date with https://github.com/produvia/ai-platform's master branch.
4. Now, copy your work from the backup taken in step 1 to the `tasks/speech/speech-synthesis` directory.
5. Push your changes to your repo
```
git add .
git commit -m "[COMMIT MESSAGE]" # insert COMMIT MESSAGE
git push
```

### Next Steps
After you take either option 1 or option 2, we can merge my fixes into your branch (if that is okay with you), and we can then create a new pull request to merge your changes into `ai-platform`.

**Comment by pritam-code-ai** [comment]
Hi,
Thank you for your reply. However, what about my other projects
contribution to produvia , I mean my pull request projects other than
speech synthesis ?

I am eagerly waiting for your reply.

Hope to hear from you soon.

Yours sincerely,
Pritam

**Comment by mlaradji** [comment]
Hi @pritam-code-ai. Can I merge this pull request then?

Your other pull requests, namely #3 and #4, cannot be merged as the repositories that were used to create the pull requests no longer exist. Please create new branches in your repository off of `produvia/master`, push your work to those branches, and then create pull requests for each of the new branches.

**Comment by pritam-code-ai** [comment]
Ok. Thank you.
However, as I am busy working on a big data science project, so I will do
your option 1 or 2 as in one of your previous message to me, at end of
December, 2019.
Yours sincerely,
Pritam

**Pull request closed without merging**
