### PR TITLE
Dimensionality Reduction

### PR DESCRIPTION
**Pull request by sravanth99**
Completed dimensionality reduction task.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@sravanth99 Thanks for opening this pull request. Please add `MLproject` to your contribution

**Comment by sravanth99** [comment]
Sure

**Comment by sravanth99** [comment]
Added MLproject

**Comment by slavakurilyak** [comment]
@sravanth99 Please add a python file (aka convert your notebook into a script), which will be triggered using `MLproject`

**Comment by sravanth99** [comment]
Done.

**Comment by sravanth99** [comment]
Added .py file and modified ML project

**Pull request closed without merging**
