### PR TITLE
Hello, It's my first contribution to the produvia open ai platform

### PR DESCRIPTION
**Pull request by zaid7860**
Age-Gender_Emotion Classifier Could be used to find whether or not customers are happy with the sale in the particular month or season, by collecting data throughout the year we can predict the best time a brand/store should go on sale, Thereby decreasing overheads and increasing Sale and profit, 
Just an example could be used in several other cases

### CODE REVIEW

**Comment by zaid7860** [comment]
Nuclei detection for medical treatment

**Comment by zaid7860** [comment]
Flower Classification

**Comment by zaid7860** [comment]
Monkey Breed Classifier,

**Comment by zaid7860** [comment]
Pull request

**Comment by slavakurilyak** [comment]
@zaid7860 This is a great starting point! Please review my comments below and make the following changes:

1. Add [MLflow](https://github.com/mlflow/mlflow) as a dependency to each task. We use [MLflow Tracking](https://mlflow.org/docs/latest/tracking.html) and [MLflow Projects](https://mlflow.org/docs/latest/projects.html) manage all AI tasks.
2. Move your nuclei detection code to the appropriate task folder: `Semantic Segmentation`. You can store this model to: `/tasks/computer-vision/semantic-segmentation`. `Semantic Segmentation` is not the same as `Image Classification` and we need to focus on solving one task at a time.
3. (Optional) See if you can abstract `input` from `output` for your `Image Classification` models. Example `input` images will be: flowers, people, monkeys. Example `output` labels will be: `flower category`, `age`, `gender`, or `monkey breed`.
4. (Optional) See if you can remove all dependencies on pre-built models and instead, build models from scratch. This will allow us to manage inputs and outputs of each model.

**Comment by zaid7860** [comment]
Okay Sir, I will do the points you mentioned and Get back to you .
Thanks

**Comment by slavakurilyak** [comment]
Check out Uber's [Ludwig](https://github.com/uber/ludwig) for inspiration on how to achieve modularity and extensibility with `inputs` and `outputs` using YAML file. Examples of Ludwig can be found [here](https://uber.github.io/ludwig/examples/).

**Comment by slavakurilyak** [comment]
@lucky-singh I would love to hear your thoughts on this pull request

**Comment by zaid7860** [comment]
Sure..

**Comment by lucky-singh** [comment]
@slavakurilyak, I agree with your [original comments](https://github.com/produvia/ai-platform/pull/2#issuecomment-502410566). As we decided to use MLflow we need to utilize it in every task. [MLflow tutorial](https://mlflow.org/docs/latest/tutorial.html) should help to kick start.

@zaid7860 , thank you for contributing into this initiative. Could you please try running [MLflow examples](https://github.com/mlflow/mlflow/tree/master/examples) once you will run few of them then pleasae try to adapt your contribution in same way. 

Imagine, each task as an AI service where a user who is unfamiler with AI can pass his/her data as input and get the desired output. Please try to update your work in this direction and make it modular and easy to use.

**Comment by zaid7860** [comment]
Roger that. Could you please help me out ?

**Comment by lucky-singh** [comment]
@zaid7860, 

MLflow site is the go-to place for documentation.
You could also check out demos on YouTube.
https://www.youtube.com/playlist?list=PLTPXxbhUt-YVstcW1-OrYoRiAipXRManO

**Comment by slavakurilyak** [comment]
@zaid7860 any updates on this pull request? You can ask implementation questions on MLflow's public Slack server: https://tinyurl.com/mlflow-slack

**Comment by zaid7860** [comment]
Hi There , hope you are doing well , I am working  on some latest
technologies  as of now ,  I can write the code bt this MLFLOW is tough to
implement. Let's see If I can help you with anything.

**Comment by slavakurilyak** [comment]
@zaid7860 Thanks for the clarification. Until [MLflow](https://github.com/mlflow/mlflow/) is integrated, I will close this pull request for now.

**Comment by zaid7860** [comment]
Okay

**Pull request closed without merging**
