### PR TITLE
Integrate MLflow with Word2Vec.

### PR DESCRIPTION
**Pull request by rajatpundir**
Hi @slavakurilyak @lucky-singh 

I just noticed that I forgot to add model logging in this pull request which I can do it the next commit.

Can you please review other changes in this pull request and suggest required changes.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@rajatpundir this looks great! Please add `mlflow.tensorflow.log_model` method into this pull request.

**Comment by rajatpundir** [comment]
It seems that this is going to be a bit challenging than I had initially anticipated as tensorflow code needs to be wrapped in a tensorflow estimator in order to use the mlflow's model logging capabilities. I will work on it, shouldn't be that difficult.

https://github.com/mlflow/mlflow/blob/master/examples/tensorflow/train_predict.py
https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator

**Comment by slavakurilyak** [comment]
@rajatpundir Are you no longer interested in developing this model? If so, please add a `TODO` note in your `README` file so other developers can pick up where you left off.

**Comment by rajatpundir** [comment]
@slavakurilyak Hi Slava, I apologize for the late reply, I have been busy in debugging some bugs in a blockchain related project in the past few weeks and really not getting the time to contribute. I saw that someone was working on the word embeddings using gensim so I did not update this branch any further. I can remove this branch for now, as the functionality is just duplicate, I guess.

**Comment by slavakurilyak** [comment]
@rajatpundir As an alternative to uploading a new model, you can also aim to improve the [existing implementation](https://github.com/produvia/ai-platform/tree/master/tasks/methodology/word-embeddings) of word embeddings. With [MLflow Tracking](https://www.mlflow.org/docs/latest/tracking.html), you can log parameters, code versions, metrics, and output files in order to improve model performance.

**Pull request closed without merging**
