### PR TITLE
Image Generation

### PR DESCRIPTION
**Pull request by jatinmandav**
I am submitting Image-Generation task using DCGANs on Fashion-MNIST dataset as part as my coding assignment. I have integrated Mlflow into the codebase as well.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@jatinmandav Thanks for your contribution. Please add `MLproject` file to your folder. Please see [MLflow examples](https://github.com/mlflow/mlflow/tree/master/examples) on how to accomplish this.

**Comment by jatinmandav** [comment]
I have added the required files.

**Comment by slavakurilyak** [comment]
@jatinmandav Thanks! Please add code usage instructions to the `README.md` file

**Comment by jatinmandav** [comment]
Updated!

**Pull request closed without merging**
