### PR TITLE
Face Generation

### PR DESCRIPTION
**Pull request by chiragbajaj25**
Face Generation on CelebA dataset using Tensorflow 2.0
I have completed the task and uploaded all the files.
Thank You.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@chiragbajaj25 Thanks for opening this pull request. Please move this to [tasks/computer-vision/face-generation](https://github.com/produvia/ai-platform/tree/master/tasks/computer-vision/face-generation) folder.

**Comment by chiragbajaj25** [comment]
I have moved the files to face-generation folder.
Thank You.

**Comment by slavakurilyak** [comment]
@chiragbajaj25 Please revert these binary files:

1. ai-platform-mlflow.jpg
2. ai-platform.jpg

**Comment by chiragbajaj25** [comment]
Done.

**Comment by mlaradji** [comment]
Hi @chiragbajaj25. Thank you for your pull request! I like the good number of passable arguments :+1:.

We would like your task to be runnable through `mlflow run .`, with the option to pass more arguments if a user wishes. To that end, I have a few comments:
1. Could you rename `MLProject` to `MLproject`? I believe `mlflow` looks for the `MLproject` file by default, and I'm unsure how to make it run a differently named project file.
2. Could you rename the "GAN" endpoint to "main", or create a new "main" endpoint? That way, the endpoint would not have to be passed when running the project.
3. I believe that the parameters in `MLProject` file have some typos.

**Comment by chiragbajaj25** [comment]
@mlaradji  thank you so much for suggesting changes. I have made the required changes and now the task is runnable through mlflow run . command.
Thank You

**Comment by slavakurilyak** [comment]
@chiragbajaj25 Thanks for making these changes

**Comment by mlaradji** [comment]
Hi @chiragbajaj25. Thank you for making the changes. The `MLproject` file looks good :+1:.

The `conda.yaml` file is missing `tqdm` and `mlflow`. I've added them locally, but I am unsure which versions are needed. When I ran `mlflow run .`, I get the cryptic exception: `ValueError: zero-size array to reduction operation minimum which has no identity`. The stack trace is attached below.
```
2019/09/29 05:24:33 INFO mlflow.projects: === Created directory /tmp/tmpz7c0mpzo for downloading remote URIs passed to arguments of type 'path' ===
2019/09/29 05:24:33 INFO mlflow.projects: === Running command 'source activate mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9 1>&2 && python GAN.py 0.0001 5 100 16 202599 256' in run with ID 'bbad66a59b994844a176d278f527ff31' === 
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2.0.0-alpha0
/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/IPython/lib/pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
  from IPython.utils.signatures import signature
Traceback (most recent call last):
  File "GAN.py", line 21, in <module>
    pyplot.imshow(helper.images_square_grid(celeba_images, 'RGB'))
  File "/content/aip-chiragbajaj25/tasks/computer-vision/face-generation/helper.py", line 108, in images_square_grid
    images = (((images - images.min()) * 255) / (images.max() - images.min())).astype(np.uint8)
  File "/root/miniconda3/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
2019/09/29 05:24:36 ERROR mlflow.cli: === Run (ID 'bbad66a59b994844a176d278f527ff31') failed ===
```

This error might be due to incompatible dependency versions in my setup.

**Comment by chiragbajaj25** [comment]
@mlaradji  the problem was that the dataset wasn't downloaded.
I have made required changes to GAN.py file.
Now the code should run smoothly.
Thank You

**Comment by mlaradji** [comment]
Hi @chiragbajaj25. Thank you for your changes. I apologize for the delay; the training takes a long time on my setup.

When running `mlflow run . -P epochs=1`, I face another `FileNotFoundError`:
```
FileNotFoundError: [Errno 2] No such file or directory: 'img/image_at_epoch_0001.png'
```
I believe this happens after the first epoch successfully finishes. It might be good to catch this `FileNotFoundError` exception so as to not stop training because of an (apparently) non-crucial component.

Also, the `mlflow` package is missing in `conda.yaml`.

#### `mlflow run . -P epochs=1` Log
```
[...]
2019/10/11 06:27:45 INFO mlflow.projects: === Created directory /tmp/tmpv1agku7k for downloading remote URIs passed to arguments of type 'path' ===
2019/10/11 06:27:45 INFO mlflow.projects: === Running command 'source activate mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9 && python GAN.py 0.0001 1 100 16 202599 256' in run with ID 'f333767923e54168bf8e829089a87750' === 
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2.0.0-alpha0
Downloading celeba: 1.44GB [02:16, 10.6MB/s]                                    
Extracting celeba...
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/IPython/lib/pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
  from IPython.utils.signatures import signature
2019-10-11 06:31:15.500931: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-11 06:31:15.991409: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3409000000 Hz
2019-10-11 06:31:16.006905: I tensorflow/compiler/xla/service/service.cc:162] XLA service 0x564cdabd5b00 executing computations on platform Host. Devices:
2019-10-11 06:31:16.006979: I tensorflow/compiler/xla/service/service.cc:169]   StreamExecutor device (0): <undefined>, <undefined>
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
tf.Tensor([[-0.00197808]], shape=(1, 1), dtype=float32)
/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/tensorflow/python/platform/tf_logging.py:161: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  get_logger().warn(msg, *args, **kwargs)
WARNING:tensorflow:Entity <function train_step at 0x7fa3c07ea950> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: AttributeError during conversion: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function train_step at 0x7fa3c07ea950> could not be transformed and will be staged without change. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: AttributeError during conversion: module 'gast' has no attribute 'Num'
Traceback (most recent call last):
  File "GAN.py", line 281, in <module>
    celeba_dataset.shape, celeba_dataset.image_mode, PARAMS['epochs'],PARAMS['batch_size'])
  File "GAN.py", line 240, in train
    seed)
  File "GAN.py", line 266, in generate_and_save_images
    plt.savefig('img/image_at_epoch_{:04d}.png'.format(epoch))
  File "/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/home/mlaradji/.conda/envs/mlflow-23927adcf49c5db593b1a3dc036e5dabcf6005a9/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'img/image_at_epoch_0001.png'
2019/10/11 08:13:54 ERROR mlflow.cli: === Run (ID 'f333767923e54168bf8e829089a87750') failed ===
```

**Comment by chiragbajaj25** [comment]
@mlaradji  Sorry for the late reply.
I think just by creating an empty folder name 'img' in the face-generation directory will solve the error.
Please kindly let me know if the problem is not solved still.
Thank You

**Pull request closed without merging**
