### PR TITLE
Image Classification

### PR DESCRIPTION
**Pull request by phdatdt**

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@phdatdt Thanks for this contribution. Please integrate [mlflow](https://mlflow.org) into your pull request.

**Comment by phdatdt** [comment]
> @phdatdt Thanks for this contribution. Please integrate [mlflow](https://mlflow.org) into your pull request.

I'm still figuring out Mlflow and working on it.

**Comment by slavakurilyak** [comment]
@phdatdt you can start by adding `MLproject` file to your pull request.

**Comment by slavakurilyak** [comment]
@phdatdt For questions related to MLflow, check out [MLflow on Slack](https://tinyurl.com/mlflow-slack)

**Pull request closed without merging**
