### PR TITLE
Sentiment Analysis

### PR DESCRIPTION
**Pull request by aminja**
First try for this part of the engine.

### CODE REVIEW

**Comment by slavakurilyak** [comment]
@aminja this is a great starting point. Please review our previous work on word2vec to avoid duplication of work and maximize code reuse.

**Comment by aminja** [comment]
Dear @slavakurilyak , I saw the code of word2vec:
We have some conflicts, I should be able to select the desired column for word2vec vectorizer.
In addition, in tweeter study case, punctuation cleaning should be optional. Also, word2vec module should return the result.

**Comment by slavakurilyak** [comment]
@ShreyasJothish what are your thoughts?

**Comment by ShreyasJothish** [comment]
> @ShreyasJothish what are your thoughts?

@slavakurilyak The code for word2vec which I contributed was specific to one particular example or use case of finding similarities between words. So @aminja example shall not be using the code as is.

**Comment by aminja** [comment]
so I believe that the committed version is fine to be reviewed.

**Comment by lucky-singh** [comment]
hi @aminja, I have made some minor modification and send a pull request to your repository. If it works for you, please accept the changes.

@huitikho, we have received similar contribution so in case other goes first, please take that as starting point.

**Comment by aminja** [comment]
@lucky-singh the desired changes are committed.

**Comment by aminja** [comment]
dear @slavakurilyak , a kindly reminder.

**Pull request closed without merging**
